### ISSUE TITLE
wie landet man hier?

### ISSUE THREAD

**Issue by alast0r** [TwitchmodsDACH/Bannlisten#2]
4l4570r bitte um die Entfernung aus der liste,  nur weil einer der Meinung ist jemand ist ein troll bedeutet dies nicht das es so ist. 
Eine liste mit beweisen wäre wünschenswert...

**Comment by TwitchmodsDACH** [comment]
https://discord.gg/e8YgSBeX86 dort wird dir geholfen , einfach joinen und einen entbannungsantrag stellen , öffentlich Daten abzulegen würde gegen den Datenschutz verstossen.
